# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
plugins: [jekyll-paginate, jemoji]
paginate: 2
paginate_path: "/blog/page:num/"
remote_theme: pages-themes/modernist@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

# Setup
title:               Giannis Kalogeropoulos
tagline:             'Personal Homepage'
description:         ''
url:                 http://github.com/jkalogero
baseurl:             ''
paginate:            2
kramdown:
  parse_block_html: true
# About/contact
author:
  name:              Giannis Kalogeropoulos
  url:               http://github.com/jkalogero
  email:             tmp@gmail.com

# Custom vars
version:             1.0.0